logging:
  level:    org: 
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinders: TRACE
              
server:  error:    include-message: always

spring:
  datasource: 
    url: jdbc:h2:file:~/prueba2h2
    username: user
    password: secret
  jpa:
    hibernate:      ddl-auto: update
  h2:
    console:      enabled: true
      path: /h2-console